### ISSUE TITLE
SDF file

### ISSUE THREAD

**Issue by AnujAgrawal7** [rickstaa/realsense-ros-gazebo#2]
Hey amazing repository. Simplifies a lot of work. 

I want to integrate the intel RealSense D435 sensor with a iris drone to run some simulation. I require the SDF file of this sensor for that. Can you guide me on how to generate then? 

I am new to URDF, XACRO and gazebo plugin. It will be really helpful if you can give me some pointers.

**Comment by rickstaa** [comment]
@AnujAgrawal7 Sorry for the late reply I oversaw your message. Hope you already solve your problem. 

To my knowledge the urdfs that are in the realsense_description package are already modified such that they contain all the tags that are required for them to work in the gazebo simulator (see this [tutorial](http://gazebosim.org/tutorials?tut=ros_urdf) and [this blog post](https://newscrewdriver.com/2018/07/31/ros-notes-urdf-vs-gazebo-sdf/) for more information). 

If you need a pure SDF file for internal use, you might have to translate the urdf file to a sdf file yourself. After a quick search, I found the following community based [sdf translation](https://github.com/intel/gazebo-realsense/blob/master/models/realsense_camera/model.sdf) which might already be enough for your usecase. If not I think you can modify it to your needs. Let me know if you have any other questions.

**Comment by AnujAgrawal7** [comment]
@rickstaa thanks! 
I found this [repository](https://github.com/mzahana/realsense_gazebo_plugin/tree/kinetic-devel) that worked for me with some minor modifications.

**Comment by rickstaa** [comment]
@AnujAgrawal7 Ah thanks for putting that repo here as a reference. Good luck with your project.
