### ISSUE TITLE
Missing RGB Data for Pointcloud

### ISSUE THREAD

**Issue by WizKhalista** [rickstaa/realsense-ros-gazebo#4]
Hey,
first of all great Repo. Good explanations and i got it easily to work. I can access a list of differrent published topics from the sensors, but what i am missing is the RGB Value of the Pointcloud. I am currently only getting grayscale values. Do you have any idea on how i could achieve getting a coloured PointCloud?
Thanks in advance!

**Comment by rickstaa** [comment]
@WizKhalista, sorry for the late response. Your message got lost in my GitHub notifications. I don't know if that is already supported. This repository is a simple wrapper that wraps the

- https://github.com/pal-robotics/realsense_gazebo_plugin
- https://github.com/IntelRealSense/realsense-ros

repositories and performs the steps described in https://github.com/issaiass/realsense2_description. In doing so, it provides an easier way to set this up. If you still need the coloured PointCloud, it is best you open an issue on https://github.com/pal-robotics/realsense_gazebo_plugin.
