### ISSUE TITLE
how to set static status?

### ISSUE THREAD

**Issue by songhat** [rickstaa/realsense-ros-gazebo#6]
I am going to put the camera floated in the air, how can I do for it ?

**Comment by rickstaa** [comment]
@songhat I apologise for the delayed response; your inquiry inadvertently escaped my attention. I hope you've resolved your problem. However, if you find the issue continues, please let me know a solution for fixing the camera.

Within the [test_d435_camera.urdf.xacro](test_d435_camera.urdf.xacro) file, kindly navigate to line 11 and effect the following modification:

```xacro
  <link name="base_link" />
```

Replace the above code snippet with the following:

```xacro
  <!-- Adjustment to Fix Camera to World -->
  <link name="world"></link>
  <joint name="base_joint" type="fixed">
      <origin xyz="0 0 1.0" rpy="0 0 0"/>
      <parent link="world"/>
      <child link="base_link"/>
  </joint>

  <link name="base_link" />
```

This adjustment introduces a new link named `world` and establishes a connection between the existing `base_link` and this newly introduced link via the `base_joint` joint. I hope this resolution is helpful to you. If you need any more help, please feel free to reach out.
